### ISSUE TITLE
unary operators inside functions don't work

### ISSUE THREAD

**Issue by valepu** [chriskonnertz/string-calc#16] opened 2018-10-27 14:14 UTC
if i run a function and the arguments after the first start with a unary operator (for example `min(5, -10)` or `min(-5, -10)` don't work while `min(-5, 10)` does ) i receive an error:

>  Notice: Undefined variable: leftOperand in /.../vendor/chriskonnertz/string-calc/src/ChrisKonnertz/StringCalc/Calculator/Calculator.php on line 117

If i wrap the arguments inside brackets it works `min(5, (-10))`
I have tested only with min and max. I'm gona do some more tests and report if i find something else

**Comment by valepu** [comment] 2018-10-27 14:20
i have noticed, by debugging, that it tries to analyze the "-" symbol by itself and in this case `isUnaryOperator` is false so it enters in the `else` branch

**Comment by chriskonnertz** [comment] 2018-10-28 19:03
Hello, I will investigate.

**Comment by chriskonnertz** [comment] 2018-10-28 19:07
Test code: https://github.com/chriskonnertz/string-calc/commit/15cb9608878e7877d7b7e862753e6e0c71caa750

Test result: https://travis-ci.org/chriskonnertz/string-calc/builds/447489420?utm_source=github_status&utm_medium=notification

Failing.

So it seems you are right. Unfortunately ;)

**Comment by valepu** [comment] 2018-10-28 23:08
Thanks for your answer and for the great library (sorry if i sounded too cold on my first message but i was in a hurry). Is there anything i can do to help? Not sure i am knowledgeable enough to make a pull request

**Comment by chriskonnertz** [comment] 2018-10-30 21:40
If you have any idea how to fix this issue do not  hesitate to let me know :) I will try to find a solution on my own but I do not know when I will be able to do so - I'm quite busy these days.

**Comment by prohalexey** [comment] 2018-11-25 12:14
Hello!
I want to use your library as a dependency for my library, but there was a bug in this lib.
So i fixed it and made PR. 
Please check it https://github.com/chriskonnertz/string-calc/pull/17

**Comment by chriskonnertz** [comment] 2018-11-26 19:31
Hello prohalexey,

thank you for your contribution! Great to see you could find the spot where the issue is located and write an update that fixes it. Good work, thank you.

I've merged your pull request and will create a new release with it.

**Closed as completed by chriskonnertz** 2018-11-26 19:31 UTC
Labels: bug
